# Generated by Django 2.2 on 2019-04-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awri', models.CharField(default='bh', max_length=20)),
                ('atime', models.DateTimeField(auto_now_add=True)),
                ('acou', models.IntegerField(default='0')),
                ('atitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tatype', models.CharField(default='标题', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(default='python', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpeo', models.CharField(default='yiyi', max_length=20)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('ctext', models.CharField(max_length=500)),
                ('cemail', models.CharField(blank=True, default='3020498522@qq.com', max_length=20, null=True)),
                ('curl', models.CharField(blank=True, default='127.0.0.1...', max_length=20, null=True)),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglook.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctxt', models.TextField()),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglook.Article')),
                ('ctag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglook.ArticleTag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='atag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglook.ArticleTag'),
        ),
        migrations.AddField(
            model_name='article',
            name='atype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglook.ArticleType'),
        ),
    ]
