# Generated by Django 2.2 on 2019-04-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloglook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(default='python', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='atag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloglook.Tag'),
        ),
    ]
